## gradle.properties 파일
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
android.enableLint=false
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17

